In [1]:
import pandas as pd 
dataset = pd.read_csv("/Users/ashrafshaik/Documents/EP1.01.csv") 

In [2]:
print(dataset.head())

   Unnamed: 0     id    event device channel  code  size  \
0           0  67635  67635.1     EP     AF3     6   260   
1           1  67636  67635.0     EP      F7     6   260   
2           2  67637  67635.0     EP      F3     6   260   
3           3  67638  67635.0     EP     FC5     6   260   
4           4  67639  67635.0     EP      T7     6   260   

                                                data  
0  4395.384615,4382.564102,4377.435897,4387.17948...  
1  4489.230769,4475.384615,4474.358974,4486.66666...  
2  4538.461538,4528.717948,4524.615384,4526.15384...  
3  4207.692307,4205.641025,4200.512820,4194.35897...  
4  4497.948717,4498.461538,4494.871794,4497.94871...  


In [3]:
dataset.iloc[0, 1] = 67635

In [4]:
print(dataset.columns)

Index(['Unnamed: 0', 'id', 'event', 'device', 'channel', 'code', 'size',
       'data'],
      dtype='object')


In [5]:
dataset = dataset.drop(columns = ['Unnamed: 0'], axis = 1)

In [6]:
print(dataset.head())

      id    event device channel  code  size  \
0  67635  67635.1     EP     AF3     6   260   
1  67636  67635.0     EP      F7     6   260   
2  67637  67635.0     EP      F3     6   260   
3  67638  67635.0     EP     FC5     6   260   
4  67639  67635.0     EP      T7     6   260   

                                                data  
0  4395.384615,4382.564102,4377.435897,4387.17948...  
1  4489.230769,4475.384615,4474.358974,4486.66666...  
2  4538.461538,4528.717948,4524.615384,4526.15384...  
3  4207.692307,4205.641025,4200.512820,4194.35897...  
4  4497.948717,4498.461538,4494.871794,4497.94871...  


In [7]:
print(dataset['size'].value_counts())

size
260    606214
256    171388
264     61586
261     44072
257     12362
252      4956
265      3640
268      2884
253       294
248       196
272       196
269        98
249        70
276        56
244        42
292        28
204        14
320        14
273        14
196        14
228        14
224        14
280        14
212        14
232        14
240        14
284        14
136        14
Name: count, dtype: int64


In [8]:
print(dataset.dtypes)

id           int64
event      float64
device      object
channel     object
code         int64
size         int64
data        object
dtype: object


In [9]:
import numpy as np
print(str(dataset.iloc[0, 6]))

4395.384615,4382.564102,4377.435897,4387.179487,4395.897435,4398.461538,4396.923076,4391.794871,4391.282051,4395.897435,4398.974358,4396.410256,4392.820512,4392.820512,4395.384615,4398.974358,4394.358974,4381.538461,4376.410256,4383.589743,4387.179487,4388.717948,4397.948717,4401.538461,4397.948717,4398.974358,4398.974358,4395.897435,4396.923076,4398.461538,4397.948717,4396.410256,4391.794871,4389.743589,4389.743589,4385.641025,4387.692307,4393.846153,4389.743589,4381.025641,4377.948717,4378.461538,4377.435897,4385.128205,4393.333333,4389.230769,4382.564102,4378.974358,4375.384615,4378.461538,4386.153846,4389.230769,4393.846153,4390.256410,4374.871794,4367.692307,4374.871794,4384.615384,4390.769230,4394.358974,4390.769230,4382.051282,4381.025641,4385.641025,4376.923076,4365.641025,4373.333333,4377.948717,4365.128205,4363.589743,4375.897435,4374.358974,4368.205128,4373.333333,4378.461538,4375.897435,4374.358974,4376.410256,4377.435897,4376.410256,4370.256410,4370.769230,4380.000000,4381

In [10]:
dataset[['device', 'channel', 'data']] = dataset[['device', 'channel', 'data']].astype('string')

In [11]:
print(dataset['size'].dtype)

int64


In [82]:
print(dataset['code'].unique())

[6 7 9 0 8 5 3 4 2 1]


In [12]:
dataset_256 = dataset.iloc[np.array(dataset['size'] == 256)]

In [13]:
print(dataset_256.head())

       id    event device channel  code  size  \
28  67663  67637.0     EP     AF3     9   256   
29  67664  67637.0     EP      F7     9   256   
30  67665  67637.0     EP      F3     9   256   
31  67666  67637.0     EP     FC5     9   256   
32  67667  67637.0     EP      T7     9   256   

                                                 data  
28  4380.512820,4389.743589,4395.897435,4395.38461...  
29  4468.717948,4480.512820,4493.333333,4490.25641...  
30  4534.871794,4545.641025,4552.820512,4551.28205...  
31  4246.666666,4256.410256,4262.564102,4250.76923...  
32  4488.717948,4491.282051,4492.820512,4491.79487...  


In [14]:
print(dataset_256.shape)

(171388, 7)


In [15]:
visual_region = np.array(dataset_256['channel'].isin(["P8", "O1", "O2"]))
dataset_256 = dataset_256.iloc[visual_region]

In [16]:
print(dataset_256.iloc[:10 , 3])

34     O1
35     O2
36     P8
118    O1
119    O2
120    P8
146    O1
147    O2
148    P8
216    O1
Name: channel, dtype: string


In [17]:
print(dataset_256.shape)

(36726, 7)


In [18]:
print(dataset_256.iloc[:16, 3:6])

    channel  code  size
34       O1     9   256
35       O2     9   256
36       P8     9   256
118      O1     6   256
119      O2     6   256
120      P8     6   256
146      O1     6   256
147      O2     6   256
148      P8     6   256
216      O1     8   256
217      O2     8   256
218      P8     8   256
244      O1     0   256
245      O2     0   256
246      P8     0   256
314      O1     1   256


In [19]:
print(dataset_256.head())

        id    event device channel  code  size  \
34   67669  67637.0     EP      O1     9   256   
35   67670  67637.0     EP      O2     9   256   
36   67671  67637.0     EP      P8     9   256   
118  67753  67643.0     EP      O1     6   256   
119  67754  67643.0     EP      O2     6   256   

                                                  data  
34   4438.974358,4440.512820,4445.128205,4445.12820...  
35   4219.487179,4224.102564,4230.256410,4231.28205...  
36   4228.205128,4229.743589,4245.128205,4248.71794...  
118  4445.641025,4458.461538,4460.512820,4449.74358...  
119  4220.000000,4226.153846,4234.871794,4230.25641...  


In [20]:
channels = np.array(dataset_256['channel'].unique())

In [21]:
print(channels)

['O1' 'O2' 'P8']


In [31]:
events = dataset_256['event'].unique().tolist()

In [32]:
print(len(events))

12242


In [33]:
eventgroups = []
for event in events:
    eventgroups.append(dataset_256[dataset_256['event'] == event])

In [34]:
print(len(eventgroups))

12242


In [35]:
eeg_data = []
for event in eventgroups:
    total_channel_data = []
    data = np.array(event['data'])
    for channel_data in data:
        total_channel_data.append(np.fromstring(channel_data, dtype=float, sep = ','))
    eeg_data.append(total_channel_data)

In [38]:
eeg_data = np.array(eeg_data)

In [39]:
print(eeg_data.shape)

(12242, 3, 256)


In [88]:
labels = []
for event in eventgroups:
    event_label = []
    event_digit = np.array(event['code'])
    labels.append(event_digit)

In [89]:
print(len(labels))

12242


In [90]:
labels = np.array(labels)

In [107]:
print(labels)

[[9 9 9]
 [6 6 6]
 [6 6 6]
 ...
 [0 0 0]
 [4 4 4]
 [4 4 4]]


In [110]:
print(labels[labels.shape[0] - 1])

[4 4 4]


In [117]:
print(encoder.transform(labels[0].reshape(3, 1)))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [118]:
from numpy import asarray
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse=False)
labels_encoded = []
encoder.fit(labels[:, i].reshape(12242, 1))
for i in range(labels.shape[0]):
    labels_encoded.append(encoder.transform(labels[i].reshape(3, 1)))
    
    
# labels = encoder.fit_transform(labels_np)
# print(labels[:5])

/Users/ashrafshaik/anaconda3/lib/python3.11/site-packages/sklearn/preprocessing/_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [119]:
labels_encoded = np.array(labels_encoded)

In [120]:
print(labels_encoded.shape)

(12242, 3, 10)


In [127]:
print(labels_encoded[0][2])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


In [133]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(eeg_data, labels_encoded, test_size = 0.2, random_state = 0)

In [134]:
print(x_train.shape)

(9793, 3, 256)


In [135]:
print(x_train[:, 0])

[[4437.948717 4432.307692 4434.358974 ... 4441.538461 4442.564102
  4440.51282 ]
 [4443.076923 4442.051282 4444.102564 ... 4449.743589 4447.179487
  4442.051282]
 [4447.692307 4444.615384 4447.179487 ... 4440.       4448.717948
  4460.51282 ]
 ...
 [4455.897435 4461.538461 4456.923076 ... 4452.820512 4457.948717
  4447.692307]
 [4443.076923 4442.564102 4450.25641  ... 4445.128205 4441.025641
  4443.076923]
 [4426.153846 4434.358974 4446.153846 ... 4437.948717 4442.051282
  4447.179487]]


In [136]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
for i in range(3):
    x_train[:, i] = sc.fit_transform(x_train[:, i])
    x_test[:, i] = sc.transform(x_test[:, i])


In [137]:
print(y_train.shape)

(9793, 3, 10)


In [138]:
print(x_train.shape)

(9793, 3, 256)


In [139]:
print(y_test.shape)

(2449, 3, 10)


In [140]:
print(x_test.shape)

(2449, 3, 256)


In [141]:
import tensorflow as tf
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=100, activation='relu'))
ann.add(tf.keras.layers.Dense(units=100, activation='relu'))
ann.add(tf.keras.layers.Dense(units=10, activation='softmax'))
ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
ann.fit(x_train, y_train, batch_size = 32, epochs = 500)

Epoch 1/500
307/307 [==============================] - 0s 692us/step - loss: 2.3451 - accuracy: 0.0997
Epoch 2/500
307/307 [==============================] - 0s 610us/step - loss: 2.3141 - accuracy: 0.1038
Epoch 3/500
307/307 [==============================] - 0s 598us/step - loss: 2.3052 - accuracy: 0.1139
Epoch 4/500
307/307 [==============================] - 0s 763us/step - loss: 2.3014 - accuracy: 0.1167
Epoch 5/500
307/307 [==============================] - 0s 782us/step - loss: 2.2969 - accuracy: 0.1179
Epoch 6/500
307/307 [==============================] - 0s 675us/step - loss: 2.2944 - accuracy: 0.1279
Epoch 7/500
307/307 [==============================] - 0s 658us/step - loss: 2.2944 - accuracy: 0.1263
Epoch 8/500
307/307 [==============================] - 0s 677us/step - loss: 2.2874 - accuracy: 0.1289
Epoch 9/500
307/307 [==============================] - 0s 667us/step - loss: 2.2822 - accuracy: 0.1360
Epoch 10/500
307/307 [==============================] - 0s 671us/step - l

307/307 [==============================] - 0s 699us/step - loss: 1.3975 - accuracy: 0.5071
Epoch 80/500
307/307 [==============================] - 0s 671us/step - loss: 1.3991 - accuracy: 0.5073
Epoch 81/500
307/307 [==============================] - 0s 711us/step - loss: 1.4108 - accuracy: 0.5010
Epoch 82/500
307/307 [==============================] - 0s 719us/step - loss: 1.3846 - accuracy: 0.5107
Epoch 83/500
307/307 [==============================] - 0s 692us/step - loss: 1.3764 - accuracy: 0.5124
Epoch 84/500
307/307 [==============================] - 0s 722us/step - loss: 1.3878 - accuracy: 0.5084
Epoch 85/500
307/307 [==============================] - 0s 717us/step - loss: 1.3659 - accuracy: 0.5164
Epoch 86/500
307/307 [==============================] - 0s 714us/step - loss: 1.3539 - accuracy: 0.5218
Epoch 87/500
307/307 [==============================] - 0s 723us/step - loss: 1.3658 - accuracy: 0.5178
Epoch 88/500
307/307 [==============================] - 0s 701us/step - loss:

307/307 [==============================] - 0s 665us/step - loss: 1.0466 - accuracy: 0.6305
Epoch 158/500
307/307 [==============================] - 0s 648us/step - loss: 1.0717 - accuracy: 0.6180
Epoch 159/500
307/307 [==============================] - 0s 662us/step - loss: 1.1021 - accuracy: 0.6079
Epoch 160/500
307/307 [==============================] - 0s 666us/step - loss: 1.0358 - accuracy: 0.6348
Epoch 161/500
307/307 [==============================] - 0s 663us/step - loss: 1.0361 - accuracy: 0.6353
Epoch 162/500
307/307 [==============================] - 0s 661us/step - loss: 1.0494 - accuracy: 0.6314
Epoch 163/500
307/307 [==============================] - 0s 643us/step - loss: 1.0451 - accuracy: 0.6289
Epoch 164/500
307/307 [==============================] - 0s 651us/step - loss: 1.0570 - accuracy: 0.6234
Epoch 165/500
307/307 [==============================] - 0s 655us/step - loss: 1.0740 - accuracy: 0.6193
Epoch 166/500
307/307 [==============================] - 0s 654us/ste

307/307 [==============================] - 0s 650us/step - loss: 0.8917 - accuracy: 0.6819
Epoch 236/500
307/307 [==============================] - 0s 649us/step - loss: 0.8792 - accuracy: 0.6859
Epoch 237/500
307/307 [==============================] - 0s 663us/step - loss: 0.9039 - accuracy: 0.6787
Epoch 238/500
307/307 [==============================] - 0s 656us/step - loss: 0.9117 - accuracy: 0.6759
Epoch 239/500
307/307 [==============================] - 0s 661us/step - loss: 0.8695 - accuracy: 0.6894
Epoch 240/500
307/307 [==============================] - 0s 664us/step - loss: 0.9001 - accuracy: 0.6771
Epoch 241/500
307/307 [==============================] - 0s 646us/step - loss: 0.8944 - accuracy: 0.6814
Epoch 242/500
307/307 [==============================] - 0s 663us/step - loss: 0.8687 - accuracy: 0.6894
Epoch 243/500
307/307 [==============================] - 0s 666us/step - loss: 0.8672 - accuracy: 0.6920
Epoch 244/500
307/307 [==============================] - 0s 660us/ste

307/307 [==============================] - 0s 648us/step - loss: 0.7933 - accuracy: 0.7127
Epoch 314/500
307/307 [==============================] - 0s 652us/step - loss: 0.8086 - accuracy: 0.7091
Epoch 315/500
307/307 [==============================] - 0s 664us/step - loss: 0.7737 - accuracy: 0.7210
Epoch 316/500
307/307 [==============================] - 0s 667us/step - loss: 0.8627 - accuracy: 0.6915
Epoch 317/500
307/307 [==============================] - 0s 666us/step - loss: 0.7832 - accuracy: 0.7186
Epoch 318/500
307/307 [==============================] - 0s 667us/step - loss: 0.8000 - accuracy: 0.7123
Epoch 319/500
307/307 [==============================] - 0s 646us/step - loss: 0.7725 - accuracy: 0.7211
Epoch 320/500
307/307 [==============================] - 0s 654us/step - loss: 0.7673 - accuracy: 0.7255
Epoch 321/500
307/307 [==============================] - 0s 660us/step - loss: 0.8432 - accuracy: 0.7001
Epoch 322/500
307/307 [==============================] - 0s 663us/ste

307/307 [==============================] - 0s 698us/step - loss: 0.8177 - accuracy: 0.7080
Epoch 392/500
307/307 [==============================] - 0s 658us/step - loss: 0.7111 - accuracy: 0.7425
Epoch 393/500
307/307 [==============================] - 0s 662us/step - loss: 0.7972 - accuracy: 0.7173
Epoch 394/500
307/307 [==============================] - 0s 660us/step - loss: 0.6837 - accuracy: 0.7537
Epoch 395/500
307/307 [==============================] - 0s 661us/step - loss: 0.6798 - accuracy: 0.7555
Epoch 396/500
307/307 [==============================] - 0s 662us/step - loss: 0.7302 - accuracy: 0.7356
Epoch 397/500
307/307 [==============================] - 0s 651us/step - loss: 0.6965 - accuracy: 0.7484
Epoch 398/500
307/307 [==============================] - 0s 663us/step - loss: 0.7166 - accuracy: 0.7383
Epoch 399/500
307/307 [==============================] - 0s 660us/step - loss: 0.7014 - accuracy: 0.7454
Epoch 400/500
307/307 [==============================] - 0s 663us/ste

307/307 [==============================] - 0s 672us/step - loss: 0.6405 - accuracy: 0.7665
Epoch 470/500
307/307 [==============================] - 0s 677us/step - loss: 0.6352 - accuracy: 0.7701
Epoch 471/500
307/307 [==============================] - 0s 662us/step - loss: 0.8003 - accuracy: 0.7132
Epoch 472/500
307/307 [==============================] - 0s 633us/step - loss: 0.7604 - accuracy: 0.7274
Epoch 473/500
307/307 [==============================] - 0s 636us/step - loss: 0.6613 - accuracy: 0.7588
Epoch 474/500
307/307 [==============================] - 0s 666us/step - loss: 0.6384 - accuracy: 0.7676
Epoch 475/500
307/307 [==============================] - 0s 651us/step - loss: 0.6799 - accuracy: 0.7523
Epoch 476/500
307/307 [==============================] - 0s 664us/step - loss: 0.6395 - accuracy: 0.7680
Epoch 477/500
307/307 [==============================] - 0s 662us/step - loss: 0.6434 - accuracy: 0.7659
Epoch 478/500
307/307 [==============================] - 0s 680us/ste

In [145]:
y_pred = ann.predict(x_test)


77/77 [==============================] - 0s 445us/step


In [146]:
print(y_pred[0])

[[8.20482910e-07 1.67515598e-22 2.37398934e-10 3.18725263e-15
  8.81563045e-10 3.36392803e-10 2.25671138e-05 4.39391888e-26
  9.99975801e-01 8.70367842e-07]
 [6.34590462e-02 5.69864525e-04 5.93345873e-02 3.72537179e-05
  1.23629728e-02 4.51885654e-07 2.17255019e-02 1.05829057e-09
  6.00597322e-01 2.41912931e-01]
 [3.21371737e-03 2.44558249e-02 1.29314944e-01 1.21215232e-01
  1.37413889e-01 1.67806551e-01 1.41322687e-01 1.34823263e-01
  1.44789675e-02 1.25954941e-01]]


In [143]:
print(y_test[:5, :10])

[[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]

 [[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]]


In [144]:
length=len(y_pred)
y_label=np.argmax(y_test,axis=1)
predict_label=np.argmax(y_pred,axis=1)

accuracy=np.sum(y_label==predict_label)/length * 100 
print("Accuracy of the dataset",accuracy )


Accuracy of the dataset 380.9309922417313


In [58]:
print(ann.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3, 100)            25700     
                                                                 
 dense_1 (Dense)             (None, 3, 100)            10100     
                                                                 
 dense_2 (Dense)             (None, 3, 10)             1010      
                                                                 
Total params: 36,810
Trainable params: 36,810
Non-trainable params: 0
_________________________________________________________________
None
